{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.2",
      "buildId": "7gqi4aagxzauxbkpytovts6a3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.19"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.7.jar",
          "url": "spring-boot-starter-2.6.7.jar",
          "size": 4770,
          "sha512": "a73d31fb5f1c295785f1d0596b37fa82650c1855863539204538443999df8f75d64e600ace35e9f5a6d8fea4121889ac3bba6d393a50e6a9d9f5acf55847e14c",
          "sha256": "0fa821f37662447f9ad3c01b0a082b4f0ff318c2ef5395c2319e889559964fee",
          "sha1": "59bd62cd60e6e7bb2a525931947c13548b207288",
          "md5": "c8b91f2c75ea3aa5ea8d884bd53a995f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.19"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.7.jar",
          "url": "spring-boot-starter-2.6.7.jar",
          "size": 4770,
          "sha512": "a73d31fb5f1c295785f1d0596b37fa82650c1855863539204538443999df8f75d64e600ace35e9f5a6d8fea4121889ac3bba6d393a50e6a9d9f5acf55847e14c",
          "sha256": "0fa821f37662447f9ad3c01b0a082b4f0ff318c2ef5395c2319e889559964fee",
          "sha1": "59bd62cd60e6e7bb2a525931947c13548b207288",
          "md5": "c8b91f2c75ea3aa5ea8d884bd53a995f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.7.jar",
          "url": "spring-boot-starter-2.6.7.jar",
          "size": 4770,
          "sha512": "a73d31fb5f1c295785f1d0596b37fa82650c1855863539204538443999df8f75d64e600ace35e9f5a6d8fea4121889ac3bba6d393a50e6a9d9f5acf55847e14c",
          "sha256": "0fa821f37662447f9ad3c01b0a082b4f0ff318c2ef5395c2319e889559964fee",
          "sha1": "59bd62cd60e6e7bb2a525931947c13548b207288",
          "md5": "c8b91f2c75ea3aa5ea8d884bd53a995f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.7.jar",
          "url": "spring-boot-starter-2.6.7.jar",
          "size": 4770,
          "sha512": "a73d31fb5f1c295785f1d0596b37fa82650c1855863539204538443999df8f75d64e600ace35e9f5a6d8fea4121889ac3bba6d393a50e6a9d9f5acf55847e14c",
          "sha256": "0fa821f37662447f9ad3c01b0a082b4f0ff318c2ef5395c2319e889559964fee",
          "sha1": "59bd62cd60e6e7bb2a525931947c13548b207288",
          "md5": "c8b91f2c75ea3aa5ea8d884bd53a995f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.7-javadoc.jar",
          "url": "spring-boot-starter-2.6.7-javadoc.jar",
          "size": 4738,
          "sha512": "d69cbc41467eb5b96146fada441f0867757e805de769c5fc84751633dedb656fe97882d28cec74f89179ee370176ef259319fb60b4a54bd7c2b1bd92f6d8cc23",
          "sha256": "9cae9580a58197a6f4c9314ca22c75e5e299dfb635fdb49225c6ebee5a25ef61",
          "sha1": "c9a956109ba3ce6c991429575a54d4a0aef1d9f0",
          "md5": "fa70785a5074a340b544d69b4f63da9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.7-sources.jar",
          "url": "spring-boot-starter-2.6.7-sources.jar",
          "size": 4737,
          "sha512": "a7e45202da5523e609867b245745cf1685bef8b36b31fec849e80e455d3f3f4089b0ce72cdbbd340ed1194d43e2f9a14c0945f83a6e7ee9384095a7cb05ac576",
          "sha256": "42c0e8868b750f93a2843a75ef480487785f449c88676e41a55b8ab0e92593ea",
          "sha1": "4358f3dcd7f3b9eb0d2e99082d6c825a733fc030",
          "md5": "de0e0bc070a77b9276f13fac54fa963b"
        }
      ]
    }
  ]
}
