services:
  mysql:
    container_name: adm_videos
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD="123456"
      - MYSQL_DATABASE=adm_videos
    security_opt:
      -  seccomp:unconfined
    ports:
      - "3308:3306"
    networks:
      - adm_videos_network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  adm_videos_network:

volumes:
  mysql-data: