{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "5.3.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.19"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.19"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.19.jar",
          "url": "spring-web-5.3.19.jar",
          "size": 1640029,
          "sha512": "fb814b2624b632d65b1f95fbbc45044d15f691d306ae58b28840e882ca31e6b2e4bdb851ff3677c8f6faafc4f15335c55d2ee8b52fe44b6261ed0015895eeeee",
          "sha256": "df65b8ce1066d2f640a547c5adade2625ff2a58371db60d50f89e1168b1fe08b",
          "sha1": "cdffc649d28d360d5891244e45277aa135ac647d",
          "md5": "af0ba70bac79aadceb87c70e9df3569d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.19"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.19"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.19.jar",
          "url": "spring-web-5.3.19.jar",
          "size": 1640029,
          "sha512": "fb814b2624b632d65b1f95fbbc45044d15f691d306ae58b28840e882ca31e6b2e4bdb851ff3677c8f6faafc4f15335c55d2ee8b52fe44b6261ed0015895eeeee",
          "sha256": "df65b8ce1066d2f640a547c5adade2625ff2a58371db60d50f89e1168b1fe08b",
          "sha1": "cdffc649d28d360d5891244e45277aa135ac647d",
          "md5": "af0ba70bac79aadceb87c70e9df3569d"
        }
      ]
    }
  ]
}
