{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.2",
      "buildId": "7gqi4aagxzauxbkpytovts6a3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.8.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.19"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.7.jar",
          "url": "spring-boot-starter-data-jpa-2.6.7.jar",
          "size": 4758,
          "sha512": "4ee1cf9e7a37da41e74187ce7937f931eb4e11c0255c158909e011ff816efd05d81ca0bea3d83a26fa2208e3bdd5705691a3da3e207c767ce8686d252f638e15",
          "sha256": "1c14d013d10bc62f02e6d89ca65bd31ccde3b1553e725f039c3b3977f7671ad4",
          "sha1": "c67c8556deb506677da64cac10c6e4edcff41847",
          "md5": "36a2d01fa76a886c60a43ed4077efed4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.8.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.19"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.7.jar",
          "url": "spring-boot-starter-data-jpa-2.6.7.jar",
          "size": 4758,
          "sha512": "4ee1cf9e7a37da41e74187ce7937f931eb4e11c0255c158909e011ff816efd05d81ca0bea3d83a26fa2208e3bdd5705691a3da3e207c767ce8686d252f638e15",
          "sha256": "1c14d013d10bc62f02e6d89ca65bd31ccde3b1553e725f039c3b3977f7671ad4",
          "sha1": "c67c8556deb506677da64cac10c6e4edcff41847",
          "md5": "36a2d01fa76a886c60a43ed4077efed4"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.7.jar",
          "url": "spring-boot-starter-data-jpa-2.6.7.jar",
          "size": 4758,
          "sha512": "4ee1cf9e7a37da41e74187ce7937f931eb4e11c0255c158909e011ff816efd05d81ca0bea3d83a26fa2208e3bdd5705691a3da3e207c767ce8686d252f638e15",
          "sha256": "1c14d013d10bc62f02e6d89ca65bd31ccde3b1553e725f039c3b3977f7671ad4",
          "sha1": "c67c8556deb506677da64cac10c6e4edcff41847",
          "md5": "36a2d01fa76a886c60a43ed4077efed4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.6.7"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.7.jar",
          "url": "spring-boot-starter-data-jpa-2.6.7.jar",
          "size": 4758,
          "sha512": "4ee1cf9e7a37da41e74187ce7937f931eb4e11c0255c158909e011ff816efd05d81ca0bea3d83a26fa2208e3bdd5705691a3da3e207c767ce8686d252f638e15",
          "sha256": "1c14d013d10bc62f02e6d89ca65bd31ccde3b1553e725f039c3b3977f7671ad4",
          "sha1": "c67c8556deb506677da64cac10c6e4edcff41847",
          "md5": "36a2d01fa76a886c60a43ed4077efed4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.6.7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.7-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.6.7-javadoc.jar",
          "size": 4749,
          "sha512": "166293ed62bcd570710ad390e871c477362bf22393562fef8ee29d15e0edcf4d473cd72d7a451fd66589ad6c2280d5d9ff8f0322482f01d051ade40a92f5c2be",
          "sha256": "a0c8bcb4561ce4056774ecd3e91454fe42735942f52db14f835c1bbdddf84bed",
          "sha1": "649a26908fcef538a0919f95813f97ce465a1c39",
          "md5": "40dc5e4304d293a73c16cddff9749bc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.7-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.6.7-sources.jar",
          "size": 4747,
          "sha512": "c0343538f69d195fd01bfa75fc21992c31663e2075db3ad1087fea7d54e2b9ee016d442a7f5a9910a7bcc176c24e27870846a940f6d138994286c2a2c9328d85",
          "sha256": "e8bfe725848327f0a9c7e780213e1afdab43031137328d0097d82ba09f60884d",
          "sha1": "20163396a08c4221ac846c268ee1a2706c4f5662",
          "md5": "44e40fe79bc2e1f83bec2899a98914af"
        }
      ]
    }
  ]
}
